### ISSUE TITLE
paasta status -v fails with JSONDecodeError

### ISSUE THREAD

**Issue by drolando** [Yelp/paasta#1080]
paasta status -s cloudflare_log_gatherer -c norcal-devc -v fails with:
```python
ERROR:__main__:Exception raised while looking at service cloudflare_log_gatherer instance worker:
ERROR:__main__:Traceback (most recent call last):
  File "/usr/bin/paasta_serviceinit", line 125, in main
    delta=args.delta,
  File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/marathon_serviceinit.py", line 430, in perform_command
    tail_lines=tail_lines,
  File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/mesos_tools.py", line 392, in status_mesos_tasks_verbose
    tail_lines=tail_lines,
  File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/mesos_tools.py", line 351, in format_task_list
    table_rows.append(format_task_row(task, get_short_task_id))
  File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/mesos_tools.py", line 252, in format_running_mesos_task_row
    get_mem_usage(task),
  File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/utils.py", line 1379, in wrapper
    result = func(*args, **kwargs)
  File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/mesos_tools.py", line 196, in get_mem_usage
    task_mem_limit = task.mem_limit
  File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/mesos/task.py", line 89, in mem_limit
    return self.stats.get("mem_limit_bytes", 0)
  File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/mesos/task.py", line 71, in stats
    return self.slave.task_stats(self["id"])
  File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/mesos/slave.py", line 99, in task_stats
    eid = self.task_executor(_id)["id"]
  File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/mesos/slave.py", line 69, in task_executor
    for fw in self.frameworks:
  File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/mesos/slave.py", line 66, in frameworks
    return util.merge(self.state, "frameworks", "completed_frameworks")
  File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/mesos/util.py", line 56, in __get__
    value = self.fget(inst)
  File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/mesos/slave.py", line 62, in state
    return self.fetch("/slave(1)/state.json").json()
  File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/requests/models.py", line 812, in json
    return json.loads(self.content.decode(encoding), **kwargs)
  File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Rob-Johnson** [comment]
@drolando I can't reproduce this today - is it still happening for you? I'd guess there was something up with the mesos slave and we don't catch the error properly

**Comment by drolando** [comment]
@Rob-Johnson yeah, today that command works fine for me too
