### ISSUE TITLE
Kazoo exceptions from API during wait-for-deployment

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#1532]
Seems like paasta-api gets disconnected from ZK occasionally and doesn't correctly recover -- it'll just return 500s until we restart it.

I'm not sure what happened to the first few lines of this traceback, but:

```
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/api/views/instance.py", line 115, in instance_status
    instance_status['marathon'] = marathon_instance_status(instance_status, service, instance, verbose)
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/api/views/instance.py", line 84, in marathon_instance_status
    marathon_job_status(mstatus, settings.marathon_client, job_config, verbose)
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/api/views/instance.py", line 47, in marathon_job_status
    app_id = job_config.format_marathon_app_dict()['id']
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/marathon_tools.py", line 398, in format_marathon_app_dict
    'instances': self.get_desired_instances(),
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/long_running_service_tools.py", line 224, in get_desired_instances
    return self.get_instances()
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/long_running_service_tools.py", line 189, in get_instances
    instance=self.instance,
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/long_running_service_tools.py", line 371, in get_instances_from_zookeeper
    with ZookeeperPool() as zookeeper_client:
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/utils.py", line 2348, in __enter__
    cls.zk.start()
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/kazoo/client.py", line 548, in start
    if self.chroot and not self.exists("/"):
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/kazoo/client.py", line 984, in exists
    return self.exists_async(path, watch).get()
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/kazoo/handlers/utils.py", line 78, in get
    raise self._exception
kazoo.exceptions.ConnectionLoss
```

and:

```
WARNING:paasta_tools.cli.cmds.mark_for_deployment:Error getting service status from PaaSTA API for nova-prod: 500ERROR: Traceback (most recent call last):
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/api/views/instance.py", line 115, in instance_status
    instance_status['marathon'] = marathon_instance_status(instance_status, service, instance, verbose)
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/api/views/instance.py", line 84, in marathon_instance_status
    marathon_job_status(mstatus, settings.marathon_client, job_config, verbose)
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/api/views/instance.py", line 47, in marathon_job_status
    app_id = job_config.format_marathon_app_dict()['id']
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/marathon_tools.py", line 398, in format_marathon_app_dict
    'instances': self.get_desired_instances(),
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/long_running_service_tools.py", line 224, in get_desired_instances
    return self.get_instances()
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/long_running_service_tools.py", line 189, in get_instances
    instance=self.instance,
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/long_running_service_tools.py", line 372, in get_instances_from_zookeeper
    (instances, _) = zookeeper_client.get('%s/instances' % compose_autoscaling_zookeeper_root(service, instance))
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/kazoo/client.py", line 1026, in get
    return self.get_async(path, watch).get()
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/kazoo/handlers/utils.py", line 72, in get
    raise self._exception
kazoo.exceptions.SessionExpiredError
```

**Comment by solarkennedy** [comment]
This is internal ticket PAASTA-12529

**Comment by EvanKrall** [comment]
I've updated the title of the issue, as this can also affect other endpoints. @mcarlson-zero found it affecting the autoscaling endpoint, which bespoke autoscalers use.

**Comment by solarkennedy** [comment]
@mattmb I think this is resolved right?
