### ISSUE TITLE
deployd crashes on startup if a marathon app exists for nonexistant service

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#1565]
I found this while working on integration tests for #1552 -- if (a) Marathon has an app defined, but there's no corresponding entry in /nail/etc/services, then startup crashes with this error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/work/paasta_tools/deployd/master.py", line 160, in run
    self.election.run(self.startup)
  File "/work/paasta_tools/deployd/leader.py", line 27, in run
    super(PaastaLeaderElection, self).run(func, *args, **kwargs)
  File "/tmp/lib/python3.6/site-packages/kazoo/recipe/election.py", line 53, in run
    func(*args, **kwargs)
  File "/work/paasta_tools/deployd/master.py", line 177, in startup
    self.prioritise_bouncing_services()
  File "/work/paasta_tools/deployd/master.py", line 257, in prioritise_bouncing_services
    failures=0,
  File "/work/paasta_tools/deployd/common.py", line 38, in __new__
    priority = cls.get_priority(service, instance, cluster)
  File "/work/paasta_tools/deployd/common.py", line 56, in get_priority
    soa_dir=DEFAULT_SOA_DIR,
  File "/work/paasta_tools/utils.py", line 132, in cache
    self.configs[key] = {'data': f(*args, **kwargs), 'fetch_time': time.time()}
  File "/work/paasta_tools/marathon_tools.py", line 405, in load_marathon_service_config
    soa_dir=soa_dir,
  File "/work/paasta_tools/marathon_tools.py", line 359, in load_marathon_service_config_no_cache
    "%s not found in config file %s/%s/%s.yaml." % (instance, soa_dir, service, marathon_conf_file),
paasta_tools.utils.NoConfigurationForServiceError: main not found in config file /nail/etc/services/test-service/marathon-testcluster.yaml.
```

In practice this would be solvable by running cleanup_marathon_jobs, but it seems like it might be a good idea to catch this.

cc @mattmb 

Probably doesn't need fixing immediately, since there's a workaround.

**Comment by EvanKrall** [comment]
Arguably this is a bug in list_marathon_service_instances.get_service_instances_that_need_bouncing, not deployd.
