### ISSUE TITLE
Marathon 'bean is not valid' errors during crossover bounce cause itest failures

### ISSUE THREAD

**Issue by Rob-Johnson** [Yelp/paasta#172]
We frequently see this from Marathon during the integration tests for the crossover bounce. This causes travis/jenkins to fail. Here is the relevant output:

```
Scenario: The crossover bounce works                                                       # bounces.feature:50
    Given a working paasta cluster                                                           # steps/setup_steps.py:104
INFO:__main__:Connecting to Marathon server at: http://172.17.0.28:8080
Given a working paasta cluster                                                           # steps/setup_steps.py:104 0.002s
    And a new healthy app to be deployed                                                     # steps/bounces_steps.py:35
And a new healthy app to be deployed                                                     # steps/bounces_steps.py:35 0.000s
    And an old app to be destroyed                                                           # steps/bounces_steps.py:61
And an old app to be destroyed                                                           # steps/bounces_steps.py:61 0.115s
    When there are 2 old healthy tasks                                                       # steps/bounces_steps.py:80
When there are 2 old healthy tasks                                                       # steps/bounces_steps.py:80 3.050s
    And deploy_service with bounce strategy "crossover" and drain method "noop" is initiated # steps/bounces_steps.py:100
crossover bounce in progress on bounce.test1. New marathon app bounce.test1.newapp.confighash not created yet. 2 new tasks to bring up. 2 old tasks receiving traffic. 0 old tasks draining. 1 old apps.
And deploy_service with bounce strategy "crossover" and drain method "noop" is initiated # steps/bounces_steps.py:100 0.049s
    Then the new app should be running                                                       # steps/bounces_steps.py:148
Then the new app should be running                                                       # steps/bounces_steps.py:148 0.006s
    And the old app should be running                                                        # steps/bounces_steps.py:148
And the old app should be running                                                        # steps/bounces_steps.py:148 0.006s
    When there are 1 new healthy tasks                                                       # steps/bounces_steps.py:80
When there are 1 new healthy tasks                                                       # steps/bounces_steps.py:80 5.087s
    And deploy_service with bounce strategy "crossover" and drain method "noop" is initiated # steps/bounces_steps.py:100
crossover bounce in progress on bounce.test1. New marathon app bounce.test1.newapp.confighash exists. 1 new tasks to bring up. 2 old tasks receiving traffic. 0 old tasks draining. 1 old apps.
And deploy_service with bounce strategy "crossover" and drain method "noop" is initiated # steps/bounces_steps.py:100 0.043s
    Then the old app should be running                                                       # steps/bounces_steps.py:148
Then the old app should be running                                                       # steps/bounces_steps.py:148 0.006s
    And the old app should be configured to have 1 instances                                 # steps/bounces_steps.py:153
And the old app should be configured to have 1 instances                                 # steps/bounces_steps.py:153 0.006s
    When there are 2 new healthy tasks                                                       # steps/bounces_steps.py:80
When there are 2 new healthy tasks                                                       # steps/bounces_steps.py:80 0.006s
    And deploy_service with bounce strategy "crossover" and drain method "noop" is initiated # steps/bounces_steps.py:100
crossover bounce in progress on bounce.test1. New marathon app bounce.test1.newapp.confighash exists. 0 new tasks to bring up. 2 old tasks receiving traffic. 0 old tasks draining. 1 old apps.
ERROR:marathon:Got HTTP 422: {"message":"Bean is not valid","errors":[{"attribute":"instances","error":"must be greater than or equal to 0"}]}
Exception raised during deploy of service bounce:
Traceback (most recent call last):
  File "/work/paasta_tools/setup_marathon_job.py", line 411, in deploy_service
    soa_dir=soa_dir,
  File "/work/paasta_tools/setup_marathon_job.py", line 246, in do_bounce
    client.kill_task(task.app_id, task.id, scale=True)
  File "/tmp/local/lib/python2.7/site-packages/marathon/client.py", line 420, in kill_task
    .format(app_id=app_id, task_id=task_id), params)
  File "/tmp/local/lib/python2.7/site-packages/marathon/client.py", line 75, in _do_request
    raise MarathonHttpError(response)
MarathonHttpError: MarathonHttpError: HTTP 422 returned with message, "Bean is not valid"
And deploy_service with bounce strategy "crossover" and drain method "noop" is initiated # steps/bounces_steps.py:100 0.067s
      Traceback (most recent call last):
        File "/tmp/local/lib/python2.7/site-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/tmp/local/lib/python2.7/site-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/work/paasta_itests/steps/bounces_steps.py", line 134, in when_deploy_service_initiated
          soa_dir=None,
        File "/work/paasta_tools/setup_marathon_job.py", line 411, in deploy_service
          soa_dir=soa_dir,
        File "/work/paasta_tools/setup_marathon_job.py", line 246, in do_bounce
          client.kill_task(task.app_id, task.id, scale=True)
        File "/tmp/local/lib/python2.7/site-packages/marathon/client.py", line 420, in kill_task
          .format(app_id=app_id, task_id=task_id), params)
        File "/tmp/local/lib/python2.7/site-packages/marathon/client.py", line 75, in _do_request
          raise MarathonHttpError(response)
      MarathonHttpError: MarathonHttpError: HTTP 422 returned with message, "Bean is not valid"
      
      Captured stderr:
      crossover bounce creating new app with app_id bounce.test1.newapp.confighash
      crossover bounce draining 1 old tasks with app_id /bounce.test1.oldapp.confighash
      crossover bounce killing drained task bounce.test1.oldapp.confighash.a77520b5-bf9d-11e5-8713-0242ac11001c
      crossover bounce draining 2 old tasks with app_id /bounce.test1.oldapp.confighash
      crossover bounce killing drained task bounce.test1.oldapp.confighash.a77547c6-bf9d-11e5-8713-0242ac11001c
      crossover bounce killing drained task bounce.test1.oldapp.confighash.a77520b5-bf9d-11e5-8713-0242ac11001c
      
      Captured logging:
      INFO:__main__:Connecting to Marathon server at: http://172.17.0.28:8080
      ERROR:marathon:Got HTTP 422: {"message":"Bean is not valid","errors":[{"attribute":"instances","error":"must be greater than or equal to 0"}]}
```

**Comment by EvanKrall** [comment]
Perhaps we could catch and ignore/retry when we get this error.

I think @solarkennedy's hypothesis about what's causing this is the double-killing (with scaling) of a task. In your output, the double-killed task is `a77520b5-bf9d-11e5-8713-0242ac11001c`. Perhaps since we're calling kill with scale=true three times for two tasks, the desired number of tasks is decremented 3 times from 2 to -1.

If that's what's happening, it's unfortunate that kill?scale=true is not idempotent for a given task, and maybe we should file an issue against Marathon for that.
