### ISSUE TITLE
Exception on cluster autoscaler run in no drain mode (when scaling down)

### ISSUE THREAD

**Issue by matthewbentley** [Yelp/paasta#1745]
```
2018-02-28 12:58:20,373:WARNING:paasta_tools.autoscaling.autoscaling_cluster_lib.SpotAutoscaler.sfr-*:Timer expired before slave ready to kill, proceding to terminate anyways
2018-02-28 12:58:20,373:ERROR:paasta_tools.autoscaling.autoscaling_cluster_lib.SpotAutoscaler.sfr-*:Timed out after 0:05:00 waiting to drain slave(1)@x.x.x.x:5051, now terminating anyway
2018-02-28 12:58:20,376:INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ec2.us-west-1.amazonaws.com
2018-02-28 12:58:20,483:ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<autoscale_cluster_resource() done, defined at /opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/autoscaling/autoscaling_cluster_lib.py:1198> exception=AssertionError('There should be only one InstanceStatus per instance',)>
Traceback (most recent call last):
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/autoscaling/autoscaling_cluster_lib.py", line 1203, in autoscale_cluster_resource
    await scaler.scale_resource(current, target)
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/autoscaling/autoscaling_cluster_lib.py", line 457, in scale_resource
    filtered_slaves = self.filter_aws_slaves(slaves_list)
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/autoscaling/autoscaling_cluster_lib.py", line 575, in filter_aws_slaves
    assert len(matching_status) == 1, "There should be only one InstanceStatus per instance"
AssertionError: There should be only one InstanceStatus per instance
```

Two issues: it happened, and then the exception was never retrieved.

**Comment by matthewbentley** [comment]
Upon running again, I couldn't reproduce this

**Comment by drmorr0** [comment]
The cluster autoscaler is deprecated in favor of Clusterman.
