### ISSUE TITLE
AttributeError in 'paasta stop'

### ISSUE THREAD

**Issue by ealter** [Yelp/paasta#1774]
```
$ paasta stop -s yelpwifi-mailer -c nova-turnstyleprod
Traceback (most recent call last):
  File "/usr/bin/paasta", line 11, in <module>                                
    load_entry_point('paasta-tools==0.69.47', 'console_scripts', 'paasta')()  
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/cli/cli.py", line 121, in main                                                      
    return_code = args.command(args)                                          
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/cli/cmds/start_stop_restart.py", line 261, in paasta_stop                           
    return paasta_start_or_stop(args, 'stop')                                 
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/cli/cmds/start_stop_restart.py", line 178, in paasta_start_or_stop                  
    pargs = apply_args_filters(args)                                          
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/cli/cmds/status.py", line 416, in apply_args_filters                                
    filters = get_filters(args)                                               
  File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/cli/cmds/status.py", line 374, in get_filters                                       
    if args.registration:                                                     
AttributeError: 'Namespace' object has no attribute 'registration'
```

**Comment by EvanKrall** [comment]
I introduced this bug in #1770, working on a branch to fix it now.
