### ISSUE TITLE
error running metastatus -vv

### ISSUE THREAD

**Issue by Rob-Johnson** [Yelp/paasta#257]
```
robj@dev22-devc:~/yelpsoa-configs/paasta_canary (master) $ paasta metastatus -vv -c norcal-stagef
Cluster: norcal-stagef
Dashboards:
  Marathon RO: xxx
  Smartstack:  xx
  Chronos RO:  xx
  Signalfx:    xx
  Mesos:     xx

Traceback (most recent call last):
  File "/usr/bin/paasta_metastatus", line 460, in <module>
    main()
  File "/usr/bin/paasta_metastatus", line 411, in main
    mesos_results = get_mesos_status(mesos_state, verbosity=args.verbose)
  File "/usr/bin/paasta_metastatus", line 289, in get_mesos_status
    metrics_results.extend(run_healthchecks_with_param(mesos_state, [assert_extra_attribute_data]))
  File "/usr/bin/paasta_metastatus", line 297, in run_healthchecks_with_param
    return [healthcheck(param) for healthcheck in healthcheck_functions]
  File "/usr/bin/paasta_metastatus", line 261, in assert_extra_attribute_data
    '%.2f' % resources_remaining['free_resources']['disk'],
TypeError: 'int' object has no attribute '__getitem__'
```

note, it works with `-vvv` and `-v`

**Comment by Rob-Johnson** [comment]
@giuliano108 want to take this?
