### ISSUE TITLE
error in check_marathon_services_replication when a task hasn't started

### ISSUE THREAD

**Issue by Rob-Johnson** [Yelp/paasta#258]
```python
check_marathon_services_replication.check_service_replication(client=client, service='profilistic', instance='kafka-tagger', cluster='norcal-devc', crit_threshold=50, soa_dir='/nail/etc/services')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/check_marathon_services_replication.py", line 260, in check_service_replication
    expected_count=expected_count,
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/check_marathon_services_replication.py", line 184, in check_healthy_marathon_tasks_for_service_instance
    num_healthy_tasks = get_healthy_marathon_instances_for_short_app_id(client, app_id)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/check_marathon_services_replication.py", line 175, in get_healthy_marathon_instances_for_short_app_id
    and datetime_from_utc_to_local(task.started_at) < one_minute_ago:
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/utils.py", line 831, in datetime_from_utc_to_local
    return datetime_convert_timezone(utc_datetime, dateutil.tz.tzutc(), dateutil.tz.tzlocal())
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/utils.py", line 835, in datetime_convert_timezone
    datetime = datetime.replace(tzinfo=from_zone)
AttributeError: 'NoneType' object has no attribute 'replace'
```

In the UI, 'started at' is None for the task - presumably causing this error

**Comment by solarkennedy** [comment]
Thanks for tracking this down. We need to get a handle on these flaps. @Rob-Johnson are you on this or would you like to have @mjksmith take it?
