### ISSUE TITLE
example_cluster docker-compose build failed

### ISSUE THREAD

**Issue by jpizagno** [Yelp/paasta#3033]
I am trying to build the example_cluster. I am on the master branch with 

Here is my setup:
```
Host OS:  Ubuntu 18
Docker version 19.03.11, build dd360c7
docker-compose version 1.27.4, build 40524192
paasta-git version:  commit 1f1dafb0216372f5a1200c1fa5f1c41f824024f9
```

I run the command:
```
docker-compose run playground
```

It fails while building itest_xenial.  

**My questions is: is this specific version of xenial-python3.6-virtualenv-pip==20.0.2 necessary?**

Here is the detailed error message while building the images:
```
Building itest_xenial
Step 1/14 : FROM ubuntu:xenial
 ---> 8185511cd5ad
Step 2/14 : ARG PIP_INDEX_URL=https://pypi.yelpcorp.com/simple
 ---> Using cache
 ---> 2a3701a7770e
Step 3/14 : ENV PIP_INDEX_URL=$PIP_INDEX_URL
 ---> Using cache
 ---> f11ae979650b
Step 4/14 : RUN sed -i 's/archive.ubuntu.com/us-east1.gce.archive.ubuntu.com/g' /etc/apt/sources.list
 ---> Using cache
 ---> c930be89e61b
Step 5/14 : RUN echo "deb http://repos.mesosphere.com/ubuntu xenial main" > /etc/apt/sources.list.d/mesosphere.list &&     apt-key adv --keyserver keyserver.ubuntu.com --recv 81026D0004C44CF7EF55ADF8DF7D54CBE56151BF
 ---> Running in f5d6857b3427
.....
Removing intermediate container 6946c9581a66
 ---> 85b5d4c2d4ce
Step 9/14 : ADD mesos-slave-secret /etc/mesos-slave-secret
 ---> c1abdd14388d
Step 10/14 : COPY requirements.txt requirements.txt
 ---> 21a3b75c7cf8
Step 11/14 : RUN python -m pip install --upgrade pip==20.0.2
 ---> Running in 51d44e9ebd0b
Collecting pip==20.0.2
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 512, in _prepare_file
    finder, self.upgrade, require_hashes)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 273, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 442, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 400, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 545, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 648, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 757, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 492, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 378, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 480, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 588, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 238, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
You are using pip version 8.1.1, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Service 'itest_xenial' failed to build : The command '/bin/sh -c python -m pip install --upgrade pip==20.0.2' returned a non-zero code: 2
```

**Comment by stug** [comment]
Interesting, I cannot reproduce this.  You might try reaching out to #compute-infra on slack?
