### ISSUE TITLE
Marathon doesn't like non-string values in constraints

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#333]
```
krall@mesos3-uswest1cdevc:~$ sudo setup_marathon_job paasta_test.main
brutal bounce in progress on paasta_test.main. New marathon app paasta--test.main.git81d2f440.confige3f94178 not created yet. 19 new tasks to bring up. 0 old tasks receiving traffic and happy. 19 old tasks unhappy. 0 old tasks draining. 1 old apps.
brutal bounce creating new app with app_id paasta--test.main.git81d2f440.confige3f94178
ERROR:marathon:Got HTTP 400: {"message":"Invalid JSON","details":[{"path":"/constraints(0)(2)","errors":["error.expected.jsstring"]}]}
Exception raised during deploy of service paasta_test:
Traceback (most recent call last):
  File "/usr/bin/setup_marathon_job", line 483, in deploy_service
    soa_dir=soa_dir,
  File "/usr/bin/setup_marathon_job", line 228, in do_bounce
    bounce_lib.create_marathon_app(marathon_jobid, config, client)
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/bounce_lib.py", line 175, in create_marathon_app
    client.create_app(app_id, MarathonApp(**config))
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/marathon/client.py", line 102, in create_app
    response = self._do_request('POST', '/v2/apps', data=data)
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/marathon/client.py", line 75, in _do_request
    raise MarathonHttpError(response)
MarathonHttpError: MarathonHttpError: HTTP 400 returned with message, "Invalid JSON"
Traceback (most recent call last):
  File "/usr/bin/setup_marathon_job", line 609, in <module>
    main()
  File "/usr/bin/setup_marathon_job", line 594, in main
    service_instance_config, soa_dir)
  File "/usr/bin/setup_marathon_job", line 540, in setup_service
    soa_dir=soa_dir,
  File "/usr/bin/setup_marathon_job", line 483, in deploy_service
    soa_dir=soa_dir,
  File "/usr/bin/setup_marathon_job", line 228, in do_bounce
    bounce_lib.create_marathon_app(marathon_jobid, config, client)
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/bounce_lib.py", line 175, in create_marathon_app
    client.create_app(app_id, MarathonApp(**config))
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/marathon/client.py", line 102, in create_app
    response = self._do_request('POST', '/v2/apps', data=data)
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/marathon/client.py", line 75, in _do_request
    raise MarathonHttpError(response)
marathon.exceptions.MarathonHttpError: MarathonHttpError: HTTP 400 returned with message, "Invalid JSON"
krall@mesos3-uswest1cdevc:~$
```

This is from a marathon.yaml that had `extra_constraints: [['hostname', 'GROUP_BY', 3]]`, so it's complaining about the 3.

We should either stringify constraint values, or reject them in our pre-receive hook.

**Comment by solarkennedy** [comment]
I vote stringify
