### ISSUE TITLE
kazoo exception from mesos.cli

### ISSUE THREAD

**Issue by ronin13** [Yelp/paasta#353]
Noticed this during a timeout:

```
  Traceback (most recent call last):
  File "/usr/bin/setup_marathon_job", line 594, in main
    service_instance_config, soa_dir)
  File "/usr/bin/setup_marathon_job", line 514, in setup_service
    marathon_app_dict = service_marathon_config.format_marathon_app_dict()
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/marathon_tools.py", line 379, in format_marathon_app_dict
    'constraints': self.get_constraints(service_namespace_config),
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/marathon_tools.py", line 296, in get_constraints
    constraints.extend(self.get_routing_constraints(service_namespace_config))
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/marathon_tools.py", line 304, in get_routing_constraints
    attribute=discover_level, blacklist=self.get_deploy_blacklist())
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/mesos_tools.py", line 473, in get_mesos_slaves_grouped_by_attribute
    mesos_state = get_mesos_state_from_leader()
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/mesos_tools.py", line 428, in get_mesos_state_from_leader
    state = master.CURRENT.state
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/mesos/cli/util.py", line 57, in __get__
    value = self.fget(inst)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/mesos/cli/master.py", line 153, in state
    return self.fetch("/master/state.json").json()
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/mesos/cli/log.py", line 44, in timer
    return fn(*args, **kwargs)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/mesos/cli/master.py", line 67, in fetch
    urlparse.urljoin(self.host, url),
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/mesos/cli/util.py", line 57, in __get__
    value = self.fget(inst)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/mesos/cli/master.py", line 61, in host
    return "{0}://{1}".format(CFG["scheme"], self.resolve(CFG["master"]))
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/mesos/cli/log.py", line 44, in timer
    return fn(*args, **kwargs)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/mesos/cli/master.py", line 145, in resolve
    return self._zookeeper_resolver(cfg)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/mesos/cli/master.py", line 80, in _zookeeper_resolver
    with zookeeper.client(hosts=hosts, read_only=True) as zk:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/mesos/cli/zookeeper.py", line 39, in client
    except kazoo.handlers.threading.TimeoutError:
AttributeError: 'module' object has no attribute 'TimeoutError'
```

This is happening because in kazoo 2.1 (and above)  TimeoutError was replaced with  KazooTimeoutError (http://kazoo.readthedocs.org/en/latest/_modules/kazoo/handlers/threading.html).

mesos-cli is tested only with kazoo 2.0 I believe (though they add >=) - https://github.com/mesosphere/mesos-cli/blob/master/setup.py#L40 

So, either we have to fix mesos.cli or  bump down the kazoo version in our deps - https://github.com/Yelp/paasta/blob/master/requirements.txt#L19

**Comment by nhandler** [comment]
We talked about this a bit earlier today. The current plan is to see if we can downgrade kazoo to 2.0.0 without causing more issues. As a short term solution, we will start a fork of mesos.cli (which is now deprecated) and patch it to properly handle this error. Longer term, we will likely need to put in the effort and get https://github.com/mesosphere/dcos-cli working.

**Comment by Rob-Johnson** [comment]
this was fixed in https://github.com/Yelp/paasta/pull/748
