### ISSUE TITLE
paasta metastatus is broken

### ISSUE THREAD

**Issue by Rob-Johnson** [Yelp/paasta#486]
```
robj@dev22-devc:~/puppet master % paasta metastatus
Cluster: everywhere-testopia
Dashboards:
  Marathon RO: http://marathon.paasta-everywhere-testopia.yelp/
  Smartstack:  http://paasta-everywhere-testopia.yelp:3212
  Chronos RO:  http://chronos.paasta-everywhere-testopia.yelp/
  Signalfx:    https://app.signalfx.com/#/dashboard/CYJklh9AYAo?sources%5B%5D=superregion:everywhere-testopia
  Mesos:       http://mesos.paasta-everywhere-testopia.yelp
Traceback (most recent call last):
  File "/usr/bin/paasta", line 120, in <module>
    main()
  File "/usr/bin/paasta", line 116, in main
    return_code = args.command(args)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/cli/cmds/metastatus.py", line 104, in paasta_metastatus
    print_cluster_status(cluster, args.verbose)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/cli/cmds/metastatus.py", line 70, in print_cluster_status
    print execute_paasta_metastatus_on_remote_master(cluster, system_paasta_config, verbose=verbose)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/cli/utils.py", line 542, in execute_paasta_metastatus_on_remote_master
    masters, output = calculate_remote_masters(cluster, system_paasta_config)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/cli/utils.py", line 413, in calculate_remote_masters
    cluster_fqdn = system_paasta_config.get_cluster_fqdn_format().format(cluster=cluster)
AttributeError: 'int' object has no attribute 'get_cluster_fqdn_format'
```

**Comment by huadongliu** [comment]
Looks like system_paasta_config is not loaded in paasta_metastatus.
