### ISSUE TITLE
paasta metastatus crashes if `dashboard_links` isn't in /etc/paasta

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#530]
```
$ paasta metastatus
Cluster: REDACTED
Traceback (most recent call last):
  File "/usr/bin/paasta", line 9, in <module>
    load_entry_point('paasta-tools==0.19.0', 'console_scripts', 'paasta')()
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/cli/cli.py", line 116, in main
    return_code = args.command(args)
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/cli/cmds/metastatus.py", line 105, in paasta_metastatus
    print_cluster_status(cluster, system_paasta_config, args.verbose)
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/cli/cmds/metastatus.py", line 69, in print_cluster_status
    print get_cluster_dashboards(cluster)
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/cli/cmds/metastatus.py", line 86, in get_cluster_dashboards
    dashboards = load_system_paasta_config().get_dashboard_links()[cluster]
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/utils.py", line 770, in get_dashboard_links
    'Could not find dashboard_links in configuration directory: %s' % self.directory)
paasta_tools.utils.PaastaNotConfiguredError: Could not find dashboard_links in configuration directory: /etc/paasta/
$
```

This should probably default to empty or something.

**Comment by koikonom** [comment]
Fixed in #570
