### ISSUE TITLE
^C does not exit paasta status -v

### ISSUE THREAD

**Issue by asottile** [Yelp/paasta#609]
I suspect `except:` somewhere.  Probably needs to be `except Exception:` or if you're explicitly trying to catch everything: `except BaseException: ... raise`

```python
$ paasta status -c norcal-stagef -v -s yelp-main
Pipeline: https://jenkins.yelpcorp.com/view/services-yelp-main

cluster: norcal-stagef
instance: ordering_swf_activity_runner
Git sha:    f75ec869 (desired)
^CERROR:__main__:Exception raised while looking at service yelp-main instance ordering_swf_activity_runner:
ERROR:__main__:Traceback (most recent call last):
  File "/usr/bin/paasta_serviceinit", line 117, in main
    delta=args.delta,
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/marathon_serviceinit.py", line 384, in perform_command
    print status_desired_state(service, instance, client, job_config)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/marathon_serviceinit.py", line 101, in status_desired_state
    status = get_bouncing_status(service, instance, client, job_config)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/marathon_serviceinit.py", line 87, in get_bouncing_status
    apps = marathon_tools.get_matching_appids(service, instance, client)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/marathon_tools.py", line 1018, in get_matching_appids
    return [app.id for app in get_matching_apps(servicename, instance, client)]
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/marathon_tools.py", line 1027, in get_matching_apps
    return [app for app in client.list_apps(embed_failures=embed_failures) if app.id.startswith(expected_prefix)]
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/marathon/client.py", line 163, in list_apps
    response = self._do_request('GET', '/v2/apps', params=params)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/marathon/client.py", line 64, in _do_request
    auth=self.auth, timeout=self.timeout)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/requests_cache/core.py", line 128, in request
    **kwargs
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/requests_cache/core.py", line 101, in send
    return send_request_and_cache_response()
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/requests_cache/core.py", line 93, in send_request_and_cache_response
    response = super(CachedSession, self).send(request, **kwargs)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1089, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 416, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 372, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt

instance: main
Git sha:    f75ec869 (desired)
^C^XERROR:__main__:Exception raised while looking at service yelp-main instance main:
ERROR:__main__:Traceback (most recent call last):
  File "/usr/bin/paasta_serviceinit", line 117, in main
    delta=args.delta,
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/marathon_serviceinit.py", line 384, in perform_command
    print status_desired_state(service, instance, client, job_config)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/marathon_serviceinit.py", line 101, in status_desired_state
    status = get_bouncing_status(service, instance, client, job_config)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/marathon_serviceinit.py", line 87, in get_bouncing_status
    apps = marathon_tools.get_matching_appids(service, instance, client)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/marathon_tools.py", line 1018, in get_matching_appids
    return [app.id for app in get_matching_apps(servicename, instance, client)]
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/marathon_tools.py", line 1027, in get_matching_apps
    return [app for app in client.list_apps(embed_failures=embed_failures) if app.id.startswith(expected_prefix)]
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/marathon/client.py", line 163, in list_apps
    response = self._do_request('GET', '/v2/apps', params=params)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/marathon/client.py", line 64, in _do_request
    auth=self.auth, timeout=self.timeout)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/requests_cache/core.py", line 128, in request
    **kwargs
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/requests_cache/core.py", line 101, in send
    return send_request_and_cache_response()
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/requests_cache/core.py", line 93, in send_request_and_cache_response
    response = super(CachedSession, self).send(request, **kwargs)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1089, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 416, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 372, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt

instance: ordering_swf_decision_runner
```

**Comment by asottile** [comment]
Needs a "maybe still a bug?" tag
