### ISSUE TITLE
paasta api with swagger client not able to handle errors

### ISSUE THREAD

**Issue by huadongliu** [Yelp/paasta#811]
paasta api uses [pyramid exception views to handle errors](https://github.com/Yelp/paasta/blob/master/paasta_tools/api/views/instance.py#L88). bravado throws exception when 404 is injected on the endpoint. 404 has been [defined in swagger.json](https://github.com/Yelp/paasta/blob/master/paasta_tools/api/api_docs/swagger.json#L72).

I am trying to use bravado config={'[also_return_response](http://bravado.readthedocs.io/en/latest/advanced.html)': True} to get http status code before interpreting results. The same exception is thrown.
 
$ USE_API_ENDPOINT=true paasta status -s robj-test-service -i main

cluster: mesosstage
Traceback (most recent call last):
  File "/nail/home/hliu/paasta/.tox/py27/bin/paasta", line 9, in <module>
    load_entry_point('paasta-tools==0.50.2', 'console_scripts', 'paasta')()
  File "/nail/home/hliu/paasta/paasta_tools/cli/cli.py", line 118, in main
    return_code = args.command(args)
  File "/nail/home/hliu/paasta/paasta_tools/cli/cmds/status.py", line 286, in paasta_status
    use_api_endpoint=use_api_endpoint
  File "/nail/home/hliu/paasta/paasta_tools/cli/cmds/status.py", line 248, in report_status
    use_api_endpoint=use_api_endpoint
  File "/nail/home/hliu/paasta/paasta_tools/cli/cmds/status.py", line 203, in report_status_for_cluster
    paasta_status_on_api_endpoint(cluster, service, instance, system_paasta_config, verbose=verbose)
  File "/nail/home/hliu/paasta/paasta_tools/cli/cmds/status.py", line 142, in paasta_status_on_api_endpoint
    status, h = client.service.status_instance(service=service, instance=instance).result()
  File "/nail/home/hliu/paasta/.tox/py27/local/lib/python2.7/site-packages/bravado/http_future.py", line 77, in result
    self.response_callbacks)
  File "/nail/home/hliu/paasta/.tox/py27/local/lib/python2.7/site-packages/bravado/http_future.py", line 126, in unmarshal_response
    raise_on_expected(incoming_response)
  File "/nail/home/hliu/paasta/.tox/py27/local/lib/python2.7/site-packages/bravado/http_future.py", line 149, in raise_on_expected
    swagger_result=http_response.swagger_result)
bravado.exception.HTTPError: 404 Not Found

**Comment by bxm156** [comment]
This is expected, if you have anything but a 200, it will be raised. Despite also_return_response. See https://github.com/Yelp/bravado/issues/251

**Comment by huadongliu** [comment]
Thanks @bxm156. 

So also_return_response is NOT really for error handling and I have to replace the following with a try-except block?
`
status, http_response = client.service.status_instance(service, instance).result()
if http_response.status_code != 200:
`

**Comment by bxm156** [comment]
something like:

try:
     ....result()
     # continue with positive 200 use case
except HTTPNotFound as exc:
   # if this is listed in your swagger responses...
   # exc.swagger_result can be accessed to get the swagger model result defined for this error
 except HTTPInternalServerError as exc:
    # Maybe this wasn't defined in your swagger reponses, so don't access .swagger_result
    # you can access things like exc.response and exc.status_code for example
 except HTTPError as exc:
   # catch-all for all swagger http errors
   # handle this error case, some http error we didn't expect..
